[project]
name = 'bitcoin_liquidity_pool'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.liquidity-pool-trait]
path = 'contracts/liquidity-pool-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.liquidity_pool]
path = 'contracts/liquidity_pool.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
